---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: posts
  label: Blog
  create: documents
  match: "**/*.md"
  templates:
  - post
- type: directory
  path: photos
  label: Fotos
  create: documents
  match: "**/*.md"
  templates:
  - photo
- type: document
  path: data/author.json
  label: Autor
- type: document
  path: data/config.json
  label: Configuraci√≥n
upload_dir: ''
public_path: https://s3.eu-west-3.amazonaws.com/soph-media
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
